version: 2.1

jobs:
  unit_tests:
    docker: 
      - image: fescrb/clang-9:v2
    steps:
      - checkout
      - run: git submodule init thirdparty/googletest
      - run: git submodule update thirparty/googletest
      - run: ci/build_and_run_unit_tests.sh

workflows:
  version: 2.1
  tests:
    jobs:
      - unit_tests