version: 2.1

jobs:
  unit_tests:
    docker: 
      - image: fescrb/root_unit_tests:latest
    steps:
      - checkout
      - run: git submodule init thirdparty/googletest
      - run: git submodule update thirdparty/googletest
      - run: git submodule init thirdparty/glfw
      - run: git submodule update thirdparty/glfw
      - run: ci/build_and_run_unit_tests.sh

workflows:
  version: 2.1
  tests:
    jobs:
      - unit_tests