version: 2.1
jobs:
  unit_tests:
    docker: 
      - image: fescrb/clang-9:v1
    steps:
      - checkout
      - run: apt update -y
      - run: apt install gyp -y
      - run: git submodule init thirdparty/googletest
      - run: git submodule update thirparty/googletest
      - run: ci/build_and_run_unit_tests.sh
