version: 2.1

jobs:
  unit_tests:
    docker: 
      - image: fescrb/clang-9:v3
    steps:
      - checkout
      - run: apt update -y
      - run: apt install libvulkan-dev libvulkan1 -y
      - run: git submodule init thirdparty/googletest
      - run: git submodule update thirdparty/googletest
      - run: ci/build_and_run_unit_tests.sh

workflows:
  version: 2.1
  tests:
    jobs:
      - unit_tests